include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Suppress all info-level messages
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
    avoid_print: ignore
    use_build_context_synchronously: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"